"""Generate lidar_density_zones.ipynb — только LiDAR density / зоны."""
import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# LiDAR: плотность точек → зоны (не depth-маска)\n",
            "\n",
            "Проецируем `input/lidar.npz` в **камеру сэмпла** (`meta.json` → `camera`, pose @ `target`).\n",
            "\n",
            "1. **hits** — сколько точек попало в пиксель (+ splat)\n",
            "2. **density_zone** — Gaussian blur по hits → «зоны» из разреженных точек\n",
            "3. **lidar_trust** — расширение от hits (**spread**, не blur)\n",
            "\n",
            "У каждого пикселя trust = f(расстояние до ближайшего hit), без смешивания «чёрной» плотности.\n",
            "`d1.npy` — только для сравнения.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import json\n",
            "import re\n",
            "import sys\n",
            "from dataclasses import dataclass\n",
            "from pathlib import Path\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "from PIL import Image\n",
            "\n",
            "REPO = Path(r\"C:/Users/adel/Documents/GitHub/YA-\")\n",
            "if str(REPO) not in sys.path:\n",
            "    sys.path.insert(0, str(REPO))\n",
            "\n",
            "from lidar_density_mask import build_lidar_density, plot_lidar_density_debug\n",
            "\n",
            "try:\n",
            "    import cv2\n",
            "except ImportError:\n",
            "    cv2 = None\n",
            "    raise ImportError(\"pip install opencv-python\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. CONFIG (пути из consensus_training)"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "CV_ROOT = Path(r\"C:/Users/adel/Downloads/cv_dataset\")\n",
            "\n",
            "@dataclass\n",
            "class LidarProbeConfig:\n",
            "    dataset_root: str = str(CV_ROOT / \"final_dataset_v5_participants/train\")\n",
            "    baked_root: str = str(CV_ROOT / \"rife_refinement_baked/train\")\n",
            "    ego_masks_root: str = str(\n",
            "        REPO / \"methods_gallery/_ego_manual_masks/masks_approved\"\n",
            "    )\n",
            "    allowed_cameras: tuple = (\"front\", \"rear\")\n",
            "    image_h: int = 544\n",
            "    image_w: int = 1024\n",
            "    use_artifact_mask: bool = True\n",
            "    # LiDAR → зоны\n",
            "    lidar_timestep: str = \"target\"\n",
            "    lidar_splat_radius: int = 2\n",
            "    lidar_zone_method: str = \"spread\"   # spread | dilate | gaussian\n",
            "    lidar_spread_radius_fine: float = 3.0   # px — spread от hit\n",
            "    lidar_spread_blur_fine: float = 1.0     # σ px blur на fine (0=выкл)\n",
            "    lidar_spread_radius: float = 14.0       # px — широкая зона\n",
            "    lidar_spread_falloff: str = \"linear\"    # linear | hard | cosine\n",
            "    lidar_zone_min: float = 0.12\n",
            "    lidar_min_hits_pixel: int = 1\n",
            "    lidar_preserve_fine: bool = True\n",
            "\n",
            "\n",
            "CFG = LidarProbeConfig()\n",
            "TARGET_HW = (CFG.image_h, CFG.image_w)\n",
            "print(\"dataset:\", CFG.dataset_root)\n",
            "print(\"baked:  \", CFG.baked_root)\n",
            "print(\"cameras:\", CFG.allowed_cameras)\n",
            "print(f\"lidar: {CFG.lidar_zone_method}  splat={CFG.lidar_splat_radius}  \"\n",
            "      f\"spread fine={CFG.lidar_spread_radius_fine} blur_f={CFG.lidar_spread_blur_fine} \"\n",
            "      f\"zone={CFG.lidar_spread_radius}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 2. Утилиты"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "VEHICLE_RE = re.compile(r\"_([a-zA-Z]+)_\\d+__\\d{3}$\")\n",
            "EPS = 1e-6\n",
            "\n",
            "\n",
            "def _parse_vehicle(sample_id: str) -> str | None:\n",
            "    m = VEHICLE_RE.search(sample_id)\n",
            "    return m.group(1) if m else None\n",
            "\n",
            "\n",
            "def _resize_hw(img, target_hw, interp):\n",
            "    H, W = target_hw\n",
            "    if img.shape[:2] == (H, W):\n",
            "        return img\n",
            "    return cv2.resize(img, (W, H), interpolation=interp)\n",
            "\n",
            "\n",
            "def _load_ego_mask(cfg, sample_id: str, camera: str, target_hw) -> np.ndarray:\n",
            "    H, W = target_hw\n",
            "    if not cfg.use_artifact_mask:\n",
            "        return np.zeros((H, W), np.float32)\n",
            "    vehicle = _parse_vehicle(sample_id)\n",
            "    if not vehicle:\n",
            "        return np.zeros((H, W), np.float32)\n",
            "    p = Path(cfg.ego_masks_root) / f\"{vehicle}_{camera}.png\"\n",
            "    if not p.is_file():\n",
            "        return np.zeros((H, W), np.float32)\n",
            "    m = np.array(Image.open(p).convert(\"L\"))\n",
            "    return (_resize_hw(m, target_hw, cv2.INTER_NEAREST) > 127).astype(np.float32)\n",
            "\n",
            "\n",
            "def build_lidar_maps(cfg, sample_dir: Path, camera: str, target_hw=TARGET_HW) -> dict:\n",
            "    return build_lidar_density(\n",
            "        sample_dir,\n",
            "        camera,\n",
            "        timestep=cfg.lidar_timestep,\n",
            "        splat_radius=cfg.lidar_splat_radius,\n",
            "        zone_method=cfg.lidar_zone_method,\n",
            "        spread_radius_fine=cfg.lidar_spread_radius_fine,\n",
            "        spread_radius=cfg.lidar_spread_radius,\n",
            "        spread_falloff=cfg.lidar_spread_falloff,\n",
            "        spread_blur_fine=cfg.lidar_spread_blur_fine,\n",
            "        zone_min=cfg.lidar_zone_min,\n",
            "        min_hits_pixel=cfg.lidar_min_hits_pixel,\n",
            "        preserve_fine=cfg.lidar_preserve_fine,\n",
            "        target_hw=target_hw,\n",
            "    )\n",
            "\n",
            "\n",
            "def list_baked_samples(cfg, camera: str | None = None) -> list[Path]:\n",
            "    out = []\n",
            "    for baked in sorted(Path(cfg.baked_root).iterdir()):\n",
            "        if not (baked / \"meta.json\").is_file():\n",
            "            continue\n",
            "        meta = json.loads((baked / \"meta.json\").read_text(encoding=\"utf-8\"))\n",
            "        cam = meta.get(\"camera\")\n",
            "        if cfg.allowed_cameras and cam not in cfg.allowed_cameras:\n",
            "            continue\n",
            "        if camera and cam != camera:\n",
            "            continue\n",
            "        src = Path(meta.get(\"source_dir\", Path(cfg.dataset_root) / meta[\"sample_id\"]))\n",
            "        if (src / \"input\" / \"lidar.npz\").is_file():\n",
            "            out.append(baked)\n",
            "    return out\n",
            "\n",
            "\n",
            "def load_sample_pack(cfg, baked_dir: Path) -> dict:\n",
            "    \"\"\"meta + src + lidar maps + rgb + ego + baked depth (для сравнения).\"\"\"\n",
            "    meta = json.loads((baked_dir / \"meta.json\").read_text(encoding=\"utf-8\"))\n",
            "    sid, cam = meta[\"sample_id\"], meta[\"camera\"]\n",
            "    src = Path(meta.get(\"source_dir\", Path(cfg.dataset_root) / sid))\n",
            "    lm = build_lidar_maps(cfg, src, cam)\n",
            "    rgb = np.array(Image.open(src / \"target\" / f\"{cam}.jpg\").convert(\"RGB\"))\n",
            "    rgb = _resize_hw(rgb, TARGET_HW, cv2.INTER_LINEAR).astype(np.float32) / 255.0\n",
            "    art = _load_ego_mask(cfg, sid, cam, TARGET_HW)\n",
            "    depth_b = None\n",
            "    dpath = baked_dir / \"d1.npy\"\n",
            "    if dpath.is_file():\n",
            "        depth_b = np.load(dpath).astype(np.float32)\n",
            "        depth_b = _resize_hw(np.where(np.isfinite(depth_b), depth_b, 0), TARGET_HW, cv2.INTER_NEAREST)\n",
            "    return dict(meta=meta, src=src, baked=baked_dir, camera=cam, sid=sid, maps=lm, rgb=rgb, art=art, depth_b=depth_b)\n",
            "\n",
            "\n",
            "BAKED_LIST = list_baked_samples(CFG)\n",
            "print(f\"сэмплов с lidar.npz ({CFG.allowed_cameras}): {len(BAKED_LIST)}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Один сэмпл — hits → зоны → lidar_trust\n",
            "\n",
            "Поменяй `PROBE_IDX` или задай `PROBE_CAMERA = \"front\"`.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "PROBE_IDX = 0\n",
            "PROBE_CAMERA = None  # например \"front\" — тогда первый front\n",
            "\n",
            "if PROBE_CAMERA:\n",
            "    _cands = [b for b in BAKED_LIST if json.loads((b / \"meta.json\").read_text())[\"camera\"] == PROBE_CAMERA]\n",
            "    baked = _cands[PROBE_IDX % len(_cands)]\n",
            "else:\n",
            "    baked = BAKED_LIST[PROBE_IDX % len(BAKED_LIST)]\n",
            "\n",
            "pack = load_sample_pack(CFG, baked)\n",
            "lm, meta, cam = pack[\"maps\"], pack[\"meta\"], pack[\"camera\"]\n",
            "\n",
            "plot_lidar_density_debug(\n",
            "    lm, rgb=pack[\"rgb\"], art=pack[\"art\"], depth_baked=pack[\"depth_b\"],\n",
            "    title=f\"{pack['sid']}  cam={cam}\",\n",
            ")\n",
            "plt.show()\n",
            "print(f\"projected: {lm['n_projected']}  hits_max={lm['hits'].max():.0f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. depth + lidar_trust − «дальнее без точек»\n",
            "\n",
            "Слева depth baked (геометрия), справа маска из **плотности LiDAR**.\n",
            "Синее = нет зоны лидара (небо / дыры) — там не доверяем depth как маске.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "lm = pack[\"maps\"]\n",
            "trust = lm[\"lidar_trust\"]\n",
            "art = pack[\"art\"]\n",
            "depth_b = pack[\"depth_b\"]\n",
            "\n",
            "lidar_valid = (trust > 0.05).astype(np.float32)\n",
            "depth_norm = np.zeros_like(depth_b, np.float32)\n",
            "if depth_b is not None:\n",
            "    v = depth_b > 0\n",
            "    if v.any():\n",
            "        depth_norm[v] = depth_b[v] / (depth_b[v].max() + EPS)\n",
            "\n",
            "scene_lidar = depth_norm * lidar_valid * (1.0 - art)\n",
            "no_lidar = 1.0 - lidar_valid\n",
            "far_void = no_lidar * (depth_norm < 0.02)  # небо: depth≈0 и нет точек\n",
            "\n",
            "fig, ax = plt.subplots(2, 4, figsize=(16, 7))\n",
            "fig.suptitle(f\"{pack['sid']}  {cam}\", fontsize=11)\n",
            "\n",
            "ax[0, 0].imshow(pack[\"rgb\"]); ax[0, 0].set_title(\"RGB target\")\n",
            "ax[0, 1].imshow(np.log1p(lm[\"hits\"]), cmap=\"hot\"); ax[0, 1].set_title(\"log(1+hits)\")\n",
            "ax[0, 2].imshow(lm[\"density_zone\"] / (lm[\"density_zone\"].max() + EPS), cmap=\"inferno\")\n",
            "ax[0, 2].set_title(\"зоны (blur)\")\n",
            "ax[0, 3].imshow(trust, cmap=\"viridis\", vmin=0, vmax=1); ax[0, 3].set_title(\"lidar_trust\")\n",
            "\n",
            "ax[1, 0].imshow(depth_norm, cmap=\"plasma\", vmin=0, vmax=1); ax[1, 0].set_title(\"depth baked\")\n",
            "ax[1, 1].imshow(lidar_valid, cmap=\"gray\", vmin=0, vmax=1); ax[1, 1].set_title(\"lidar valid\")\n",
            "ax[1, 2].imshow(scene_lidar, cmap=\"plasma\", vmin=0, vmax=1); ax[1, 2].set_title(\"depth × lidar × (1-ego)\")\n",
            "ax[1, 3].imshow(np.maximum(no_lidar, far_void), cmap=\"Blues\", vmin=0, vmax=1)\n",
            "ax[1, 3].set_title(\"RIFE-зона: нет лидара / небо\")\n",
            "\n",
            "for a in ax.ravel():\n",
            "    a.axis(\"off\")\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "pct = dict(\n",
            "    trust_gt_025=100 * (trust > 0.25).mean(),\n",
            "    no_lidar=100 * no_lidar.mean(),\n",
            "    far_void=100 * far_void.mean(),\n",
            "    ego=100 * art.mean(),\n",
            ")\n",
            "print(\"% пикселей:\", \", \".join(f\"{k}={v:.1f}\" for k, v in pct.items()))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Подбор spread_radius / splat (на том же сэмпле)\n",
            "\n",
            "Сравни **spread** (градиент от hit) vs старый **gaussian**.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "src, cam = pack[\"src\"], pack[\"camera\"]\n",
            "radii = [4, 8, 12, 18, 24]\n",
            "methods = [\"spread\", \"gaussian\", \"dilate\"]\n",
            "\n",
            "fig, axes = plt.subplots(len(methods), len(radii), figsize=(2.6 * len(radii), 2.6 * len(methods)))\n",
            "fig.suptitle(f\"trust  {pack['sid']}\", fontsize=10)\n",
            "for i, meth in enumerate(methods):\n",
            "    for j, r in enumerate(radii):\n",
            "        kw = dict(\n",
            "            splat_radius=CFG.lidar_splat_radius, zone_method=meth,\n",
            "            spread_radius_fine=CFG.lidar_spread_radius_fine,\n",
            "            spread_radius=r, zone_min=CFG.lidar_zone_min, target_hw=TARGET_HW,\n",
            "        )\n",
            "        if meth == \"gaussian\":\n",
            "            kw[\"zone_sigma\"] = r\n",
            "            kw[\"zone_sigma_fine\"] = CFG.lidar_spread_radius_fine\n",
            "        m = build_lidar_density(src, cam, **kw)\n",
            "        axes[i, j].imshow(m[\"lidar_trust\"], cmap=\"viridis\", vmin=0, vmax=1)\n",
            "        axes[i, j].set_title(f\"{meth} r={r}\", fontsize=7)\n",
            "        axes[i, j].axis(\"off\")\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Несколько сэмплов (front / rear)\n",
            "\n",
            "Быстрый просмотр 6 примеров.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "N_SHOW = 6\n",
            "step = max(1, len(BAKED_LIST) // N_SHOW)\n",
            "fig, axes = plt.subplots(2, N_SHOW, figsize=(2.8 * N_SHOW, 5))\n",
            "for col, bi in enumerate(range(0, len(BAKED_LIST), step)[:N_SHOW]):\n",
            "    p = load_sample_pack(CFG, BAKED_LIST[bi])\n",
            "    t = p[\"maps\"][\"lidar_trust\"]\n",
            "    axes[0, col].imshow(p[\"rgb\"])\n",
            "    axes[0, col].set_title(p[\"camera\"], fontsize=8)\n",
            "    axes[1, col].imshow(t, cmap=\"viridis\", vmin=0, vmax=1)\n",
            "    axes[1, col].set_title(p[\"sid\"][-8:], fontsize=7)\n",
            "    for r in range(2):\n",
            "        axes[r, col].axis(\"off\")\n",
            "plt.suptitle(\"RGB / lidar_trust\", fontsize=10)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
]

out = Path(__file__).parent / "lidar_density_zones.ipynb"
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print("Wrote", out)
