"""Generate lidar_rife_blend.ipynb — маска r3+blur и blend model/RIFE."""
import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# LiDAR r3+blur → линейный blend Model + RIFE\n",
            "\n",
            "**Маска:** только `spread_radius_fine=3` + `spread_blur_fine≈1` (без широкой zone).\n",
            "\n",
            "**Blend:** где `lidar_trust ≥ mask_thr` → `α·model + (1−α)·rife`, иначе **RIFE**.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import json\n",
            "import sys\n",
            "from dataclasses import dataclass\n",
            "from pathlib import Path\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import torch\n",
            "from PIL import Image\n",
            "\n",
            "REPO = Path(r\"C:/Users/adel/Documents/GitHub/YA-\")\n",
            "if str(REPO) not in sys.path:\n",
            "    sys.path.insert(0, str(REPO))\n",
            "\n",
            "import importlib\n",
            "import consensus_kit\n",
            "importlib.reload(consensus_kit)\n",
            "from consensus_kit import (\n",
            "    ConsensusConfig,\n",
            "    ConsensusDataset,\n",
            "    default_config,\n",
            "    discover_samples,\n",
            "    make_split,\n",
            "    load_consensus_model,\n",
            "    psnr_uint8_np,\n",
            "    tensor_to_hwc_rgb,\n",
            ")\n",
            "from lidar_density_mask import build_lidar_density, blend_model_rife_lidar, lidar_trust_for_sample\n",
            "\n",
            "try:\n",
            "    import cv2\n",
            "except ImportError:\n",
            "    cv2 = None\n",
            "\n",
            "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(DEVICE)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. CONFIG"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "CFG = default_config()\n",
            "CFG.allowed_cameras = (\"front\", \"rear\")\n",
            "\n",
            "# LiDAR: только r3 + лёгкий blur\n",
            "CFG.lidar_zone_method = \"spread\"\n",
            "CFG.lidar_spread_radius_fine = 3.0\n",
            "CFG.lidar_spread_blur_fine = 1.0\n",
            "CFG.lidar_spread_radius = 0.0\n",
            "CFG.lidar_zone_min = 0.12\n",
            "\n",
            "CKPT_PATH = REPO / \"checkpoints_consensus\" / \"consensus_unet_best.pt\"\n",
            "USE_EMA = True\n",
            "\n",
            "BLEND_ALPHA = 0.55          # вес модели в зоне лидара\n",
            "MASK_THR = CFG.lidar_zone_min\n",
            "\n",
            "PROBE_IDX = 0\n",
            "PROBE_CAMERA = None         # \"front\" / \"rear\" / None\n",
            "\n",
            "VAL_FRACTION = 0.16\n",
            "VAL_SEED = 42\n",
            "VAL_SUBSET = 0              # 0 = весь val; иначе первые N для быстрого прогона\n",
            "\n",
            "print(f\"lidar: r={CFG.lidar_spread_radius_fine} blur={CFG.lidar_spread_blur_fine}  thr={MASK_THR}\")\n",
            "print(f\"blend α={BLEND_ALPHA}  ckpt={CKPT_PATH.is_file()}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 2. Сэмпл + маска lidar_trust"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def pick_baked(cfg, idx=0, camera=None):\n",
            "    out = []\n",
            "    for baked in sorted(Path(cfg.baked_root).iterdir()):\n",
            "        if not (baked / \"meta.json\").is_file():\n",
            "            continue\n",
            "        meta = json.loads((baked / \"meta.json\").read_text(encoding=\"utf-8\"))\n",
            "        cam = meta.get(\"camera\")\n",
            "        if cfg.allowed_cameras and cam not in cfg.allowed_cameras:\n",
            "            continue\n",
            "        if camera and cam != camera:\n",
            "            continue\n",
            "        src = Path(meta.get(\"source_dir\", Path(cfg.dataset_root) / meta[\"sample_id\"]))\n",
            "        if (src / \"input\" / \"lidar.npz\").is_file():\n",
            "            out.append(baked)\n",
            "    if not out:\n",
            "        raise FileNotFoundError(\"нет baked с lidar.npz\")\n",
            "    return out[idx % len(out)]\n",
            "\n",
            "\n",
            "baked_dir = pick_baked(CFG, PROBE_IDX, PROBE_CAMERA)\n",
            "meta = json.loads((baked_dir / \"meta.json\").read_text(encoding=\"utf-8\"))\n",
            "src = Path(meta.get(\"source_dir\", Path(CFG.dataset_root) / meta[\"sample_id\"]))\n",
            "cam = meta[\"camera\"]\n",
            "hw = (CFG.image_h, CFG.image_w)\n",
            "\n",
            "lm = build_lidar_density(\n",
            "    src, cam, target_hw=hw,\n",
            "    zone_method=\"spread\",\n",
            "    spread_radius_fine=CFG.lidar_spread_radius_fine,\n",
            "    spread_blur_fine=CFG.lidar_spread_blur_fine,\n",
            "    spread_radius=0,\n",
            "    fine_only=True,\n",
            "    zone_min=CFG.lidar_zone_min,\n",
            "    spike_trust=1.0,\n",
            ")\n",
            "trust = lm[\"lidar_trust\"]\n",
            "print(meta[\"sample_id\"], cam, \"projected\", lm[\"n_projected\"])\n",
            "print(f\"trust>thr: {(trust >= MASK_THR).mean()*100:.1f}%\")\n",
            "\n",
            "fig, ax = plt.subplots(1, 3, figsize=(12, 3.5))\n",
            "ax[0].imshow(np.log1p(lm[\"hits\"]), cmap=\"hot\"); ax[0].set_title(\"hits\")\n",
            "ax[1].imshow(lm[\"density_fine\"], cmap=\"viridis\", vmin=0, vmax=1); ax[1].set_title(\"r3+blur\")\n",
            "ax[2].imshow(trust, cmap=\"viridis\", vmin=0, vmax=1); ax[2].set_title(\"trust\")\n",
            "for a in ax: a.axis(\"off\")\n",
            "plt.tight_layout(); plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. Model + RIFE → blend по маске"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "if not CKPT_PATH.is_file():\n",
            "    raise FileNotFoundError(f\"Нет чекпоинта {CKPT_PATH}\")\n",
            "\n",
            "model, _ = load_consensus_model(CKPT_PATH, DEVICE, use_ema=USE_EMA, cfg=CFG)\n",
            "model.eval()\n",
            "\n",
            "ds = ConsensusDataset([baked_dir], CFG, augment=False)\n",
            "batch = ds[0]\n",
            "with torch.no_grad():\n",
            "    inp = batch[\"inputs\"].unsqueeze(0).to(DEVICE)\n",
            "    msk = batch[\"effective_mask\"].unsqueeze(0).to(DEVICE)\n",
            "    base = batch[\"base_init\"].unsqueeze(0).to(DEVICE)\n",
            "    with torch.autocast(device_type=DEVICE.type, dtype=torch.bfloat16, enabled=DEVICE.type == \"cuda\"):\n",
            "        pred = model(inp, msk, base)[\"pred\"].float()\n",
            "\n",
            "model_rgb = tensor_to_hwc_rgb(pred)\n",
            "rife_rgb = tensor_to_hwc_rgb(batch[\"rife_rgb\"])\n",
            "gt_rgb = tensor_to_hwc_rgb(batch[\"target\"])\n",
            "\n",
            "blended = blend_model_rife_lidar(model_rgb, rife_rgb, trust, alpha=BLEND_ALPHA, mask_thr=MASK_THR)\n",
            "\n",
            "p_model = psnr_uint8_np(model_rgb, gt_rgb)\n",
            "p_rife = psnr_uint8_np(rife_rgb, gt_rgb)\n",
            "p_blend = psnr_uint8_np(blended, gt_rgb)\n",
            "print(f\"PSNR model={p_model:.2f}  RIFE={p_rife:.2f}  blend={p_blend:.2f}  (α={BLEND_ALPHA})\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 4. Визуализация"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "has = (trust >= MASK_THR)[..., None]\n",
            "\n",
            "fig, ax = plt.subplots(2, 4, figsize=(16, 7))\n",
            "fig.suptitle(f\"{meta['sample_id']}  α={BLEND_ALPHA}  lidar≥{MASK_THR}\", fontsize=11)\n",
            "\n",
            "ax[0, 0].imshow(gt_rgb); ax[0, 0].set_title(\"GT\")\n",
            "ax[0, 1].imshow(model_rgb); ax[0, 1].set_title(f\"model {p_model:.1f} dB\")\n",
            "ax[0, 2].imshow(rife_rgb); ax[0, 2].set_title(f\"RIFE {p_rife:.1f} dB\")\n",
            "ax[0, 3].imshow(blended); ax[0, 3].set_title(f\"blend {p_blend:.1f} dB\")\n",
            "\n",
            "ax[1, 0].imshow(trust, cmap=\"viridis\", vmin=0, vmax=1); ax[1, 0].set_title(\"lidar_trust\")\n",
            "ax[1, 1].imshow(has[..., 0], cmap=\"gray\", vmin=0, vmax=1); ax[1, 1].set_title(\"mask\")\n",
            "ax[1, 2].imshow(np.where(has, blended, 0)); ax[1, 2].set_title(\"blend в маске\")\n",
            "ax[1, 3].imshow(np.where(~has, rife_rgb, 0)); ax[1, 3].set_title(\"RIFE вне маски\")\n",
            "for a in ax.ravel():\n",
            "    a.axis(\"off\")\n",
            "plt.tight_layout(); plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 5. Перебор α (только в зоне лидара)"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "alphas = np.linspace(0, 1, 11)\n",
            "psnrs = []\n",
            "for a in alphas:\n",
            "    out = blend_model_rife_lidar(model_rgb, rife_rgb, trust, alpha=float(a), mask_thr=MASK_THR)\n",
            "    psnrs.append(psnr_uint8_np(out, gt_rgb))\n",
            "best_i = int(np.argmax(psnrs))\n",
            "print(\"α → PSNR:\", \", \".join(f\"{a:.2f}:{p:.2f}\" for a, p in zip(alphas, psnrs)))\n",
            "print(f\"best α={alphas[best_i]:.2f}  PSNR={psnrs[best_i]:.2f}\")\n",
            "\n",
            "fig, ax = plt.subplots(1, 6, figsize=(14, 2.8))\n",
            "for i, a in enumerate([0.0, 0.35, 0.55, 0.75, 1.0, alphas[best_i]]):\n",
            "    out = blend_model_rife_lidar(model_rgb, rife_rgb, trust, alpha=float(a), mask_thr=MASK_THR)\n",
            "    ax[i].imshow(out)\n",
            "    ax[i].set_title(f\"α={a:.2f}\", fontsize=9)\n",
            "    ax[i].axis(\"off\")\n",
            "plt.suptitle(\"blend в маске / RIFE вне\", fontsize=10)\n",
            "plt.tight_layout(); plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Val split (как в consensus_training)\n",
            "\n",
            "Тот же `val_fraction=0.16`, `seed=42`, камеры front/rear.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "ALL_SAMPLES = discover_samples(CFG)\n",
            "_, VAL_PATHS = make_split(ALL_SAMPLES, VAL_FRACTION, VAL_SEED)\n",
            "if VAL_SUBSET > 0:\n",
            "    VAL_PATHS = VAL_PATHS[:VAL_SUBSET]\n",
            "print(f\"val: {len(VAL_PATHS)} / {len(ALL_SAMPLES)} samples\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Прогон val: model + RIFE + lidar_trust\n",
            "\n",
            "Один проход inference на каждый val-сэмпл (долго ~1–2 мин на GPU для ~70 кадров).",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "HW = (CFG.image_h, CFG.image_w)\n",
            "val_cache = []\n",
            "\n",
            "for i, baked_dir in enumerate(VAL_PATHS):\n",
            "    meta = json.loads((baked_dir / \"meta.json\").read_text(encoding=\"utf-8\"))\n",
            "    src = Path(meta.get(\"source_dir\", Path(CFG.dataset_root) / meta[\"sample_id\"]))\n",
            "    cam = meta[\"camera\"]\n",
            "    trust = lidar_trust_for_sample(\n",
            "        src, cam, HW,\n",
            "        spread_radius_fine=CFG.lidar_spread_radius_fine,\n",
            "        spread_blur_fine=CFG.lidar_spread_blur_fine,\n",
            "        zone_min=CFG.lidar_zone_min,\n",
            "    )\n",
            "    ds = ConsensusDataset([baked_dir], CFG, augment=False)\n",
            "    batch = ds[0]\n",
            "    with torch.no_grad():\n",
            "        inp = batch[\"inputs\"].unsqueeze(0).to(DEVICE)\n",
            "        msk = batch[\"effective_mask\"].unsqueeze(0).to(DEVICE)\n",
            "        base = batch[\"base_init\"].unsqueeze(0).to(DEVICE)\n",
            "        with torch.autocast(device_type=DEVICE.type, dtype=torch.bfloat16, enabled=DEVICE.type == \"cuda\"):\n",
            "            pred = model(inp, msk, base)[\"pred\"].float()\n",
            "    val_cache.append({\n",
            "        \"meta\": meta,\n",
            "        \"model\": tensor_to_hwc_rgb(pred),\n",
            "        \"rife\": tensor_to_hwc_rgb(batch[\"rife_rgb\"]),\n",
            "        \"gt\": tensor_to_hwc_rgb(batch[\"target\"]),\n",
            "        \"trust\": trust,\n",
            "    })\n",
            "    if (i + 1) % 10 == 0 or i + 1 == len(VAL_PATHS):\n",
            "        print(f\"  {i+1}/{len(VAL_PATHS)}  {meta['sample_id'][:40]}...\", flush=True)\n",
            "\n",
            "b_model = np.mean([psnr_uint8_np(e[\"model\"], e[\"gt\"]) for e in val_cache])\n",
            "b_rife = np.mean([psnr_uint8_np(e[\"rife\"], e[\"gt\"]) for e in val_cache])\n",
            "print(f\"val mean PSNR  model={b_model:.3f}  RIFE={b_rife:.3f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 8. Перебор α на всём val"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "ALPHAS = np.round(np.linspace(0, 1, 21), 2)\n",
            "mean_psnr = []\n",
            "for a in ALPHAS:\n",
            "    ps = [\n",
            "        psnr_uint8_np(\n",
            "            blend_model_rife_lidar(e[\"model\"], e[\"rife\"], e[\"trust\"], alpha=float(a), mask_thr=MASK_THR),\n",
            "            e[\"gt\"],\n",
            "        )\n",
            "        for e in val_cache\n",
            "    ]\n",
            "    mean_psnr.append(float(np.mean(ps)))\n",
            "    print(f\"  α={a:.2f}  mean PSNR={mean_psnr[-1]:.3f}  ΔRIFE={mean_psnr[-1]-b_rife:+.3f}\")\n",
            "\n",
            "best_i = int(np.argmax(mean_psnr))\n",
            "BEST_ALPHA = float(ALPHAS[best_i])\n",
            "print(f\"\\nBEST α={BEST_ALPHA:.2f}  mean PSNR={mean_psnr[best_i]:.3f}  (model={b_model:.3f}  RIFE={b_rife:.3f})\")\n",
            "\n",
            "fig, ax = plt.subplots(1, 1, figsize=(8, 4))\n",
            "ax.plot(ALPHAS, mean_psnr, \"o-\", label=\"lidar-mask blend\")\n",
            "ax.axhline(b_model, color=\"C1\", ls=\"--\", label=f\"model only ({b_model:.2f})\")\n",
            "ax.axhline(b_rife, color=\"C2\", ls=\"--\", label=f\"RIFE only ({b_rife:.2f})\")\n",
            "ax.axvline(BEST_ALPHA, color=\"gray\", ls=\":\", label=f\"best α={BEST_ALPHA:.2f}\")\n",
            "ax.set_xlabel(\"α (model weight in lidar zone)\")\n",
            "ax.set_ylabel(\"mean PSNR val\")\n",
            "ax.legend(fontsize=8)\n",
            "ax.grid(True, alpha=0.3)\n",
            "plt.tight_layout(); plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 9. Визуализация лучшего α на нескольких val-примерах"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "SHOW_IDX = [0, len(val_cache)//3, 2*len(val_cache)//3]\n",
            "fig, axes = plt.subplots(len(SHOW_IDX), 5, figsize=(14, 3.2 * len(SHOW_IDX)))\n",
            "if len(SHOW_IDX) == 1:\n",
            "    axes = axes[None, :]\n",
            "fig.suptitle(f\"best α={BEST_ALPHA:.2f}  thr={MASK_THR}\", fontsize=11)\n",
            "\n",
            "for row, vi in enumerate(SHOW_IDX):\n",
            "    e = val_cache[vi]\n",
            "    blend = blend_model_rife_lidar(e[\"model\"], e[\"rife\"], e[\"trust\"], alpha=BEST_ALPHA, mask_thr=MASK_THR)\n",
            "    p = psnr_uint8_np(blend, e[\"gt\"])\n",
            "    sid = e[\"meta\"][\"sample_id\"][-12:]\n",
            "    imgs = [e[\"gt\"], e[\"model\"], e[\"rife\"], blend, e[\"trust\"]]\n",
            "    titles = [\"GT\", \"model\", \"RIFE\", f\"blend {p:.1f}dB\", \"trust\"]\n",
            "    for col in range(5):\n",
            "        if col == 4:\n",
            "            axes[row, col].imshow(imgs[col], cmap=\"viridis\", vmin=0, vmax=1)\n",
            "        else:\n",
            "            axes[row, col].imshow(imgs[col])\n",
            "        axes[row, col].set_title(f\"{titles[col]}\\n{sid}\" if col == 0 else titles[col], fontsize=8)\n",
            "        axes[row, col].axis(\"off\")\n",
            "plt.tight_layout(); plt.show()\n",
        ],
    },
]

out = Path(__file__).parent / "lidar_rife_blend.ipynb"
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print("Wrote", out)
