"""Generate consensus_ensemble_front_rear.ipynb."""
import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Ансамбль: Consensus U-Net (front/rear) + RIFE\n",
            "\n",
            "Перебор коэффициентов смешивания предсказания модели и RIFE на **val**-сплите\n",
            "(тот же `seed=42`, `val_fraction=0.16`, что в `consensus_training.ipynb`).\n",
            "\n",
            "**Базовые режимы:**\n",
            "- `linear`: `α·model + (1-α)·rife`\n",
            "- `cov_soft`: `cov^γ·model + (1-cov^γ)·rife`\n",
            "- `cov_gate`: где `cov ≥ thr` → model, иначе RIFE\n",
            "- `alpha_cov`: `w = α + β·cov`, затем `w·model + (1-w)·rife`\n",
            "- `conf_gate`: по `confidence` голове модели (если есть в чекпоинте)\n",
            "- **depth_trust**: модель в средней зоне глубины при валидном лидаре + coverage;\n",
            "  RIFE — ego, близко, **далеко без лидара**, низкий cov\n",
            "- **aniso smooth**: Perona-Malik / structure-tensor на выходе модели перед blend\n",
            "- **pipeline**: smooth → depth blend → опционально linear\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import sys\n",
            "from pathlib import Path\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import torch\n",
            "\n",
            "REPO = Path(r\"C:/Users/adel/Documents/GitHub/YA-\")\n",
            "if str(REPO) not in sys.path:\n",
            "    sys.path.insert(0, str(REPO))\n",
            "\n",
            "import importlib\n",
            "import consensus_kit\n",
            "importlib.reload(consensus_kit)  # после правок kit — без перезапуска kernel\n",
            "from consensus_kit import (\n",
            "    CONSENSUS_KIT_VERSION,\n",
            "    ConsensusConfig,\n",
            "    anisotropic_diffusion_rgb,\n",
            "    blend_alpha_cov,\n",
            "    blend_conf_gate,\n",
            "    blend_cov_gate,\n",
            "    blend_cov_soft,\n",
            "    blend_depth_band,\n",
            "    blend_depth_cov,\n",
            "    blend_depth_soft,\n",
            "    blend_depth_trust,\n",
            "    blend_linear,\n",
            "    blend_pipeline,\n",
            "    default_config,\n",
            "    depth_model_weight,\n",
            "    depth_trust_decompose,\n",
            "    discover_samples,\n",
            "    plot_depth_trust_debug,\n",
            "    effective_depth,\n",
            "    eval_cache_psnr,\n",
            "    load_consensus_model,\n",
            "    make_split,\n",
            "    preprocess_model,\n",
            "    psnr_uint8_np,\n",
            "    infer_and_save_val_cache,\n",
            "    load_val_cache,\n",
            "    run_inference_cache,\n",
            "    save_val_cache,\n",
            "    structure_tensor_aniso_smooth,\n",
            ")\n",
            "\n",
            "assert CONSENSUS_KIT_VERSION >= 5, f\"Обновите consensus_kit.py (version={CONSENSUS_KIT_VERSION})\"\n",
            "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(DEVICE, \"consensus_kit v\", CONSENSUS_KIT_VERSION)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# --- пути (не перезаписывает side-чекпоинты) ---\n",
            "CFG = default_config()\n",
            "CFG.allowed_cameras = (\"front\", \"rear\")\n",
            "\n",
            "CKPT_PATH = REPO / \"checkpoints_consensus\" / \"consensus_unet_best.pt\"\n",
            "USE_EMA = True\n",
            "CACHE_NPY = REPO / \"checkpoints_consensus\" / \"val_cache_front_rear.npz\"  # опционально\n",
            "REBUILD_CACHE = False  # True — пересобрать (долго); False — load с диска\n",
            "CACHE_COMPRESS = False  # True = savez_compressed (очень медленно на 544×1024)\n",
            "\n",
            "VAL_SUBSET = 0  # 0 = весь val; иначе первые N для быстрого прогона\n",
            "\n",
            "print(f\"ckpt: {CKPT_PATH}\")\n",
            "print(f\"exists: {CKPT_PATH.is_file()}\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "all_samples = discover_samples(CFG)\n",
            "_, val_paths = make_split(all_samples, CFG.val_fraction, CFG.seed)\n",
            "if VAL_SUBSET > 0:\n",
            "    val_paths = val_paths[:VAL_SUBSET]\n",
            "print(f\"val samples: {len(val_paths)} / {len(all_samples)} total\")\n",
            "\n",
            "if not CKPT_PATH.is_file():\n",
            "    raise FileNotFoundError(f\"Нет чекпоинта: {CKPT_PATH}\\nСначала обучи consensus_training.ipynb\")\n",
            "\n",
            "model, ckpt_meta = load_consensus_model(CKPT_PATH, DEVICE, use_ema=USE_EMA, cfg=CFG)\n",
            "vp = ckpt_meta.get(\"val_psnr_ema\", ckpt_meta.get(\"val_psnr\"))\n",
            "print(f\"loaded  val_psnr (from ckpt): {vp}\")\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "CACHE_PATH = CACHE_NPY.with_suffix(\".npz\")\n",
            "\n",
            "if REBUILD_CACHE or not CACHE_PATH.is_file():\n",
            "    cache = infer_and_save_val_cache(\n",
            "        model, val_paths, CFG, DEVICE, CACHE_PATH,\n",
            "        compress=CACHE_COMPRESS,\n",
            "    )\n",
            "else:\n",
            "    cache = load_val_cache(CACHE_PATH)\n",
            "\n",
            "if \"depth\" not in cache[0] or \"lidar_trust\" not in cache[0]:\n",
            "    raise RuntimeError(\"В кэше нет depth/lidar_trust — REBUILD_CACHE=True и пересобери\")\n",
            "\n",
            "# baselines\n",
            "b_model = eval_cache_psnr(cache, lambda e: e[\"model\"])\n",
            "b_rife = eval_cache_psnr(cache, lambda e: e[\"rife\"])\n",
            "b_base = eval_cache_psnr(cache, lambda e: e[\"base\"])\n",
            "print(f\"model only: {b_model:.3f} dB\")\n",
            "print(f\"RIFE only:  {b_rife:.3f} dB\")\n",
            "print(f\"base_init:  {b_base:.3f} dB\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. Линейный ансамбль `α·model + (1-α)·rife`"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "alphas = np.linspace(0, 1, 21)\n",
            "rows = []\n",
            "for a in alphas:\n",
            "    p = eval_cache_psnr(cache, lambda e, a=a: blend_linear(e[\"model\"], e[\"rife\"], a))\n",
            "    rows.append({\"alpha\": a, \"psnr\": p, \"d_vs_rife\": p - b_rife, \"d_vs_model\": p - b_model})\n",
            "df_linear = pd.DataFrame(rows)\n",
            "best_lin = df_linear.loc[df_linear[\"psnr\"].idxmax()]\n",
            "print(df_linear.sort_values(\"psnr\", ascending=False).head(8).to_string(index=False))\n",
            "print(f\"\\nBEST linear α={best_lin['alpha']:.2f}  PSNR={best_lin['psnr']:.3f} dB\")\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(8, 4))\n",
            "ax.plot(df_linear[\"alpha\"], df_linear[\"psnr\"], \"o-\", label=\"ensemble\")\n",
            "ax.axhline(b_model, color=\"C1\", ls=\"--\", label=f\"model ({b_model:.2f})\")\n",
            "ax.axhline(b_rife, color=\"C2\", ls=\"--\", label=f\"RIFE ({b_rife:.2f})\")\n",
            "ax.set_xlabel(\"α (вес модели)\")\n",
            "ax.set_ylabel(\"PSNR dB\")\n",
            "ax.set_title(\"Linear blend on val\")\n",
            "ax.legend()\n",
            "ax.grid(True, alpha=0.3)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Coverage: мягкое смешивание и порог\n",
            "\n",
            "Идея: в зонах с хорошим warp (высокий `coverage`) больше доверять модели, в дырках — RIFE.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# cov_soft: gamma\n",
            "gammas = [0.5, 1.0, 1.5, 2.0, 3.0]\n",
            "for g in gammas:\n",
            "    p = eval_cache_psnr(cache, lambda e, g=g: blend_cov_soft(e[\"model\"], e[\"rife\"], e[\"cov\"], g))\n",
            "    print(f\"cov_soft γ={g:.1f}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}\")\n",
            "\n",
            "print()\n",
            "for thr in np.linspace(0.1, 0.9, 9):\n",
            "    p = eval_cache_psnr(cache, lambda e, t=thr: blend_cov_gate(e[\"model\"], e[\"rife\"], e[\"cov\"], t))\n",
            "    print(f\"cov_gate thr={thr:.2f}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. 2D сетка `α + β·coverage`"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "alphas_1d = np.linspace(0, 0.6, 13)\n",
            "betas = np.linspace(0, 1.2, 13)\n",
            "grid = np.zeros((len(betas), len(alphas_1d)))\n",
            "for i, b in enumerate(betas):\n",
            "    for j, a in enumerate(alphas_1d):\n",
            "        grid[i, j] = eval_cache_psnr(\n",
            "            cache,\n",
            "            lambda e, a=a, b=b: blend_alpha_cov(e[\"model\"], e[\"rife\"], e[\"cov\"], a, b),\n",
            "        )\n",
            "ij = np.unravel_index(grid.argmax(), grid.shape)\n",
            "print(f\"BEST α={alphas_1d[ij[1]]:.2f} β={betas[ij[0]]:.2f}  PSNR={grid[ij]:.3f} dB\")\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(9, 6))\n",
            "im = ax.imshow(grid, aspect=\"auto\", origin=\"lower\", cmap=\"viridis\",\n",
            "               extent=[alphas_1d[0], alphas_1d[-1], betas[0], betas[-1]])\n",
            "plt.colorbar(im, ax=ax, label=\"PSNR dB\")\n",
            "ax.set_xlabel(\"α (базовый вес модели)\")\n",
            "ax.set_ylabel(\"β (усиление от coverage)\")\n",
            "ax.set_title(\"α + β·cov blend\")\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 4. Confidence gate (если есть в чекпоинте)"],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "has_conf = \"conf\" in cache[0]\n",
            "print(f\"confidence map in cache: {has_conf}\")\n",
            "if has_conf:\n",
            "    for thr in np.linspace(0.3, 0.9, 13):\n",
            "        p = eval_cache_psnr(cache, lambda e, t=thr: blend_conf_gate(e[\"model\"], e[\"rife\"], e[\"conf\"], t))\n",
            "        print(f\"conf_gate thr={thr:.2f}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}\")\n",
            "else:\n",
            "    print(\"Пропуск — модель не сохранила confidence в кэш (пересобери REBUILD_CACHE=True)\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Анизотропное сглаживание выхода модели\n",
            "\n",
            "Перед blend убираем шум/артефакты сети, сохраняя границы. `pm` = Perona-Malik;\n",
            "`tensor` = диффузия вдоль структуры (structure tensor). В ego-зоне диффузия слабее.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "for method in (\"none\", \"pm\", \"tensor\"):\n",
            "    if method == \"tensor\":\n",
            "        fn = lambda e: preprocess_model(e[\"model\"], \"tensor\", depth=e[\"depth\"], art=e[\"art\"], n_iter=5, step=0.15)\n",
            "    elif method == \"pm\":\n",
            "        fn = lambda e: preprocess_model(e[\"model\"], \"pm\", depth=e[\"depth\"], art=e[\"art\"], n_iter=8, kappa=0.06)\n",
            "    else:\n",
            "        fn = lambda e: e[\"model\"]\n",
            "    p = eval_cache_psnr(cache, fn)\n",
            "    print(f\"smooth={method:6s}  PSNR(model→GT)={p:.3f}  Δraw={p-b_model:+.3f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Смешивание по depth + ego + лидар\n",
            "\n",
            "`depth_trust`: трапеция по depth × **`lidar_trust`** (плотность LiDAR) × coverage.\n",
            "**Модель** — средняя дистанция с точками лидара и хорошим warp.\n",
            "**RIFE** — ego, близко, **очень далеко без лидара** (небо/дырки), низкий cov.",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 6a. Проверка: depth + маски − «дальнее»\n",
            "\n",
            "Смотри по шагам: норм. depth → lidar/ego/cov → трапеция → итог `w_model`.\n",
            "Красное — **близко** (RIFE), синее — **дальнее без лидара** (небо/дырки), последний кадр — где уходит в RIFE (`1−w_model`).\n",
            "Поменяй `DEBUG_IDX` и пороги `D_LO` / `D_HI` / `COV_MIN`.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from consensus_kit import depth_trust_decompose, plot_depth_trust_debug\n",
            "\n",
            "DEBUG_IDX = 0          # индекс в val cache\n",
            "D_LO, D_HI = 0.12, 0.68\n",
            "D_PEAK_LO, D_PEAK_HI = 0.28, 0.52\n",
            "COV_MIN = 0.12\n",
            "\n",
            "e_dbg = cache[DEBUG_IDX]\n",
            "sid = e_dbg[\"meta\"].get(\"sample_id\", DEBUG_IDX)\n",
            "fig, dec = plot_depth_trust_debug(\n",
            "    e_dbg,\n",
            "    d_lo=D_LO, d_peak_lo=D_PEAK_LO, d_peak_hi=D_PEAK_HI, d_hi=D_HI,\n",
            "    cov_min=COV_MIN,\n",
            "    title=f\"{sid}  cam={e_dbg['meta'].get('camera', '?')}\",\n",
            ")\n",
            "plt.show()\n",
            "\n",
            "# Сводка: depth «сцены» = depth × lidar × (1−ego); что вычитаем как «дальнее»\n",
            "fig2, ax2 = plt.subplots(1, 4, figsize=(14, 3.2))\n",
            "ax2[0].imshow(e_dbg[\"depth\"][0] if e_dbg[\"depth\"].ndim == 3 else e_dbg[\"depth\"], cmap=\"plasma\")\n",
            "ax2[0].set_title(\"depth\")\n",
            "ax2[1].imshow(dec[\"depth_scene\"], cmap=\"plasma\")\n",
            "ax2[1].set_title(\"depth × lidar × (1−ego)\")\n",
            "far_cut = np.maximum(dec[\"mask_far_void\"], dec[\"mask_far_geom\"])\n",
            "ax2[2].imshow(dec[\"depth_scene\"] * (1.0 - far_cut), cmap=\"plasma\")\n",
            "ax2[2].set_title(\"сцена − дальнее (geom|void)\")\n",
            "if \"gt\" in e_dbg:\n",
            "    gt = e_dbg[\"gt\"]\n",
            "    if gt.ndim == 3 and gt.shape[0] == 3:\n",
            "        gt = gt.transpose(1, 2, 0)\n",
            "    ax2[3].imshow(np.clip(gt, 0, 1))\n",
            "    ax2[3].set_title(\"GT\")\n",
            "else:\n",
            "    ax2[3].imshow(dec[\"w_final\"], cmap=\"viridis\", vmin=0, vmax=1)\n",
            "    ax2[3].set_title(\"w_model\")\n",
            "for a in ax2:\n",
            "    a.axis(\"off\")\n",
            "plt.suptitle(f\"depth + маска − дальнее  |  {sid}\", fontsize=10)\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Несколько val-примеров подряд\n",
            "for j in [0, len(cache)//4, len(cache)//2]:\n",
            "    if j >= len(cache):\n",
            "        continue\n",
            "    plot_depth_trust_debug(cache[j], d_lo=D_LO, d_hi=D_HI, cov_min=COV_MIN,\n",
            "        title=cache[j][\"meta\"].get(\"sample_id\", j))\n",
            "    plt.show()\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "print(\"--- depth_soft (legacy, монотонный) ---\")\n",
            "for g in (0.8, 1.0, 1.2, 1.5, 2.0):\n",
            "    p = eval_cache_psnr(cache, lambda e, g=g: blend_depth_soft(e[\"model\"], e[\"rife\"], e[\"depth\"], e[\"art\"], gamma=g))\n",
            "    print(f\"  γ={g:.1f}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}\")\n",
            "\n",
            "print(\"\\n--- depth_trust (трапеция + valid + cov) ---\")\n",
            "best_db = (-1, None)\n",
            "for d_lo in (0.08, 0.12, 0.16):\n",
            "    for d_hi in (0.62, 0.68, 0.74):\n",
            "        for cov_min in (0.0, 0.12, 0.2):\n",
            "            p = eval_cache_psnr(\n",
            "                cache,\n",
            "                lambda e, a=d_lo, b=d_hi, cm=cov_min: blend_depth_trust(\n",
            "                    e[\"model\"], e[\"rife\"], e[\"depth\"], e[\"cov\"], e[\"art\"],\n",
            "                    lidar_trust=e.get(\"lidar_trust\"), d_lo=a, d_hi=b, cov_min=cm,\n",
            "                ),\n",
            "            )\n",
            "            if p > best_db[0]:\n",
            "                best_db = (p, dict(d_lo=d_lo, d_hi=d_hi, cov_min=cov_min))\n",
            "            print(f\"  lo={d_lo:.2f} hi={d_hi:.2f} cov_min={cov_min:.2f}  PSNR={p:.3f}\")\n",
            "print(f\"BEST depth_trust: {best_db[1]}  PSNR={best_db[0]:.3f}\")\n",
            "\n",
            "print(\"\\n--- depth_trust × gamma_c ---\")\n",
            "for gc in (0.8, 1.0, 1.2, 1.5):\n",
            "    p = eval_cache_psnr(\n",
            "        cache,\n",
            "        lambda e, gc=gc, kw=best_db[1]: blend_depth_trust(\n",
            "            e[\"model\"], e[\"rife\"], e[\"depth\"], e[\"cov\"], e[\"art\"],\n",
            "            lidar_trust=e.get(\"lidar_trust\"), gamma_c=gc, **kw,\n",
            "        ),\n",
            "    )\n",
            "    print(f\"  γ_c={gc}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Полный pipeline: aniso → depth → linear\n",
            "\n",
            "Комбинируем лучшие идеи: сгладить модель, смешать по depth/art, при необходимости\n",
            "добавить линейный с RIFE (α из секции 1).",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "DEPTH_KW = best_db[1]  # dict d_lo, d_hi, cov_min из секции 6\n",
            "LIN_ALPHA = float(best_lin[\"alpha\"])  # из секции 1\n",
            "\n",
            "pipelines = {\n",
            "    \"depth_only\": dict(smooth=\"none\", blend=\"depth_trust\", blend_kwargs=dict(**DEPTH_KW)),\n",
            "    \"pm+depth\": dict(smooth=\"pm\", smooth_kwargs=dict(n_iter=8, kappa=0.06), blend=\"depth_trust\", blend_kwargs=dict(**DEPTH_KW)),\n",
            "    \"pm+depth+linear\": dict(smooth=\"pm\", smooth_kwargs=dict(n_iter=8, kappa=0.06), blend=\"depth_trust\", blend_kwargs=dict(**DEPTH_KW), linear_alpha=LIN_ALPHA),\n",
            "    \"pm+depth_cov\": dict(smooth=\"pm\", smooth_kwargs=dict(n_iter=6, kappa=0.07), blend=\"depth_trust\", blend_kwargs=dict(**DEPTH_KW, gamma_c=1.2)),\n",
            "}\n",
            "for name, kw in pipelines.items():\n",
            "    p = eval_cache_psnr(cache, lambda e, kw=kw: blend_pipeline(e, **kw))\n",
            "    print(f\"{name:20s}  PSNR={p:.3f}  ΔRIFE={p-b_rife:+.3f}  Δlinear={p-float(best_lin['psnr']):+.3f}\")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 8. Визуализация pipeline\n",
            "\n",
            "Подставь имя лучшего pipeline из секции 7.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "PIPELINE_KW = pipelines[\"pm+depth+linear\"]  # или другой ключ\n",
            "BEST_BLEND = lambda e: blend_pipeline(e, **PIPELINE_KW)\n",
            "BEST_ALPHA = PIPELINE_KW.get(\"linear_alpha\", LIN_ALPHA)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 9. Визуализация (как в линейном α)\n",
            "\n",
            "Подставь свои лучшие параметры из сеток выше.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def show_compare(entry, title_extra=\"\"):\n",
            "    gt, r = entry[\"gt\"], entry[\"rife\"]\n",
            "    m = preprocess_model(entry[\"model\"], PIPELINE_KW.get(\"smooth\", \"none\"), depth=entry.get(\"depth\"), art=entry.get(\"art\"), **PIPELINE_KW.get(\"smooth_kwargs\", {}))\n",
            "    ens = BEST_BLEND(entry)\n",
            "    meta = entry[\"meta\"]\n",
            "    err_m = np.abs(m - gt).mean(axis=2)\n",
            "    err_r = np.abs(r - gt).mean(axis=2)\n",
            "    err_e = np.abs(ens - gt).mean(axis=2)\n",
            "    win = err_r > err_e + 0.01  # зелёный = ансамбль лучше RIFE\n",
            "    fig, axes = plt.subplots(2, 4, figsize=(16, 7))\n",
            "    fig.suptitle(f\"{meta['sample_id'][:50]}… | {meta['camera']} {title_extra}\", fontsize=10)\n",
            "    for ax, img, t in zip(\n",
            "        axes[0],\n",
            "        [gt, r, m, ens],\n",
            "        [\"GT\", f\"RIFE {psnr_uint8_np(r,gt):.2f}\", f\"model(smooth) {psnr_uint8_np(m,gt):.2f}\", f\"pipeline {psnr_uint8_np(ens,gt):.2f}\"],\n",
            "    ):\n",
            "        ax.imshow(np.clip(img, 0, 1))\n",
            "        ax.set_title(t, fontsize=9)\n",
            "        ax.axis(\"off\")\n",
            "    for ax, err, t in zip(axes[1, :3], [err_r, err_m, err_e], [\"|RIFE-GT|\", \"|model-GT|\", \"|ens-GT|\"]):\n",
            "        ax.imshow(err, cmap=\"hot\", vmin=0, vmax=0.25)\n",
            "        ax.set_title(t, fontsize=9)\n",
            "        ax.axis(\"off\")\n",
            "    wm = np.full(err_e.shape + (3,), 0.5)\n",
            "    wm[win] = [0.15, 0.85, 0.15]\n",
            "    axes[1, 3].imshow(wm)\n",
            "    axes[1, 3].set_title(f\"ens<RIFE {100*win.mean():.1f}% px\", fontsize=9)\n",
            "    axes[1, 3].axis(\"off\")\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "\n",
            "# лучший и худший по PSNR ансамбля\n",
            "scored = [(i, psnr_uint8_np(BEST_BLEND(e), e[\"gt\"])) for i, e in enumerate(cache)]\n",
            "scored.sort(key=lambda x: x[1])\n",
            "print(\"worst:\", scored[0][1], \"best:\", scored[-1][1])\n",
            "for idx, ps in [scored[0], scored[len(scored)//2], scored[-1]]:\n",
            "    show_compare(cache[idx], f\"PSNR={ps:.2f}\")\n",
        ],
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out = Path(__file__).resolve().parent / "consensus_ensemble_front_rear.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Wrote {out}")
